# RootChain MVP - GitHub Project Configuration
# This file defines the project structure for tracking MVP development

project:
  name: "RootChain MVP"
  description: "Production-ready blockchain platform with native ROOT token support"
  url: "https://github.com/BronzonTech-Cloud/rootchain"

# Project Board Configuration
board:
  columns:
    - name: "Backlog"
      description: "Tasks waiting to be started"
    - name: "Phase 1 - Foundation"
      description: "Security, infrastructure, and core setup (Weeks 1-12)"
    - name: "Phase 2 - Core Features"
      description: "Transaction system, explorer, developer portal (Weeks 13-24)"
    - name: "Phase 3 - Advanced Features"
      description: "Smart contracts, DeFi, enterprise features (Weeks 25-36)"
    - name: "Phase 4 - Production"
      description: "Security audit, monitoring, launch prep (Weeks 37-48)"
    - name: "In Progress"
      description: "Currently being worked on"
    - name: "Review"
      description: "Ready for review and testing"
    - name: "Done"
      description: "Completed tasks"

# Labels Configuration
labels:
  # Priority Labels
  - name: "P0-Critical"
    color: "d73a4a"
    description: "Critical priority - blocks MVP launch"
  - name: "P1-High"
    color: "f66a0a"
    description: "High priority - important for MVP"
  - name: "P2-Medium"
    color: "fbca04"
    description: "Medium priority - nice to have"
  - name: "P3-Low"
    color: "0e8a16"
    description: "Low priority - future consideration"

  # Phase Labels
  - name: "Phase-1"
    color: "7057ff"
    description: "Phase 1 - Foundation (Weeks 1-12)"
  - name: "Phase-2"
    color: "0e8a16"
    description: "Phase 2 - Core Features (Weeks 13-24)"
  - name: "Phase-3"
    color: "ff6b35"
    description: "Phase 3 - Advanced Features (Weeks 25-36)"
  - name: "Phase-4"
    color: "d73a4a"
    description: "Phase 4 - Production (Weeks 37-48)"

  # Type Labels
  - name: "mvp"
    color: "1d76db"
    description: "MVP related task"
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"
  - name: "documentation"
    color: "0075ca"
    description: "Improvements or additions to documentation"
  - name: "security"
    color: "b60205"
    description: "Security related issue"
  - name: "performance"
    color: "ff6b6b"
    description: "Performance related issue"
  - name: "testing"
    color: "28a745"
    description: "Testing related task"

  # Component Labels
  - name: "blockchain-core"
    color: "c2e0c6"
    description: "Blockchain core functionality"
  - name: "wallet"
    color: "c5def5"
    description: "Wallet system"
  - name: "api"
    color: "d4c5f9"
    description: "API endpoints and services"
  - name: "frontend"
    color: "f9d0c4"
    description: "Frontend applications"
  - name: "database"
    color: "fef2c0"
    description: "Database related"
  - name: "infrastructure"
    color: "e1e4e8"
    description: "Infrastructure and deployment"
  - name: "monitoring"
    color: "bfd4f2"
    description: "Monitoring and logging"

# Milestones Configuration
milestones:
  - title: "Phase 1 - Foundation Complete"
    description: "Security fixes, database integration, advanced API functionality, smart contract framework"
    due_on: "2024-05-15T00:00:00Z"
    state: "open"
  - title: "Phase 2 - Core Features Complete"
    description: "Transaction system, explorer, developer portal, mobile applications"
    due_on: "2024-08-15T00:00:00Z"
    state: "open"
  - title: "Phase 3 - Advanced Features Complete"
    description: "Smart contracts, DeFi features, enterprise features, community tools"
    due_on: "2024-11-15T00:00:00Z"
    state: "open"
  - title: "Phase 4 - Production Ready"
    description: "Security audit, monitoring, launch preparation, community launch"
    due_on: "2025-02-15T00:00:00Z"
    state: "open"
  - title: "MVP Launch"
    description: "Production launch of RootChain MVP"
    due_on: "2025-02-28T00:00:00Z"
    state: "open"

# Automation Rules
automation:
  # Auto-assign labels based on issue content
  label_rules:
    - if: "title contains '[SEC]' or body contains 'security'"
      then: "add labels: ['security', 'P0-Critical']"
    - if: "title contains '[API]' or body contains 'api'"
      then: "add labels: ['api', 'mvp']"
    - if: "title contains '[WALLET]' or body contains 'wallet'"
      then: "add labels: ['wallet', 'mvp']"
    - if: "title contains '[BC]' or body contains 'blockchain'"
      then: "add labels: ['blockchain-core', 'mvp']"
    - if: "title contains '[FRONTEND]' or body contains 'frontend'"
      then: "add labels: ['frontend', 'mvp']"

  # Auto-move issues based on labels
  move_rules:
    - if: "has label 'Phase-1'"
      then: "move to 'Phase 1 - Foundation'"
    - if: "has label 'Phase-2'"
      then: "move to 'Phase 2 - Core Features'"
    - if: "has label 'Phase-3'"
      then: "move to 'Phase 3 - Production'"
    - if: "has label 'P0-Critical'"
      then: "move to 'In Progress'"

# Project Metrics
metrics:
  - name: "Velocity"
    description: "Tasks completed per week"
    target: 10
  - name: "Bug Rate"
    description: "Bugs per 100 tasks"
    target: 5
  - name: "Test Coverage"
    description: "Percentage of code covered by tests"
    target: 90
  - name: "Security Issues"
    description: "Number of open security issues"
    target: 0

# Team Configuration
team:
  lead: "BronzonTech-Cloud"
  members:
    - "BronzonTech-Cloud"
    - "developer-1"
    - "developer-2"
  
  roles:
    - name: "Project Lead"
      responsibilities: ["Project management", "Architecture decisions", "Code review"]
    - name: "Backend Developer"
      responsibilities: ["API development", "Blockchain core", "Database"]
    - name: "Frontend Developer"
      responsibilities: ["UI/UX", "React/Next.js", "User experience"]
    - name: "DevOps Engineer"
      responsibilities: ["Infrastructure", "Deployment", "Monitoring"]

# Communication
communication:
  channels:
    - name: "General Discussion"
      type: "GitHub Discussions"
      url: "https://github.com/BronzonTech-Cloud/projects/discussions"
    - name: "Bug Reports"
      type: "GitHub Issues"
      url: "https://github.com/BronzonTech-Cloud/projects/issues"
    - name: "Feature Requests"
      type: "GitHub Issues"
      url: "https://github.com/BronzonTech-Cloud/projects/issues"
  
  meetings:
    - name: "Daily Standup"
      frequency: "Daily"
      time: "9:00 AM EST"
    - name: "Sprint Planning"
      frequency: "Weekly"
      time: "Monday 10:00 AM EST"
    - name: "Sprint Review"
      frequency: "Weekly"
      time: "Friday 3:00 PM EST"
    - name: "Retrospective"
      frequency: "Bi-weekly"
      time: "Friday 4:00 PM EST"
