version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  blockchain:
    build:
      context: .
      dockerfile: Dockerfile.blockchain
    ports:
      - "8545:8545"
    environment:
      - ENVIRONMENT=development
    depends_on:
      - redis

  wallet-backend:
    build:
      context: .
      dockerfile: Dockerfile.wallet-backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - REDIS_HOST=redis
    depends_on:
      - redis

volumes:
  redis-data:
