name: Bug Report
about: Create a bug report for the MVP
title: '[BUG] '
labels: ['bug', 'mvp']
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        # Bug Report
        
        Use this template to report a bug in the RootChain MVP.

  - type: input
    id: phase
    attributes:
      label: Phase
      description: Which phase is this bug related to?
      placeholder: 'Phase 1, Phase 2, or Phase 3'
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System down, data loss)
        - High (Major functionality broken)
        - Medium (Minor functionality affected)
        - Low (Cosmetic issue)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: 'Describe the bug...'
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: 'Describe what should happen...'
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: 'Describe what actually happened...'
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Environment details
      placeholder: |
        - OS: [e.g. Windows 10, macOS 12, Ubuntu 20.04]
        - Browser: [e.g. Chrome 91, Firefox 89]
        - Node.js version: [e.g. 16.14.0]
        - Python version: [e.g. 3.12.0]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Any relevant logs or error messages
      placeholder: 'Paste any relevant logs or error messages here...'

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem
      placeholder: 'Add screenshots here...'

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: 'Add any other context about the problem here...'
