name: MVP Task
about: Create a new MVP development task
title: '[MVP] '
labels: ['mvp', 'task']
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        # MVP Task Creation
        
        Use this template to create a new MVP development task.

  - type: input
    id: phase
    attributes:
      label: Phase
      description: Which phase does this task belong to?
      placeholder: 'Phase 1, Phase 2, or Phase 3'
    validations:
      required: true

  - type: input
    id: priority
    attributes:
      label: Priority
      description: Task priority level
      placeholder: 'P0 (Critical), P1 (High), P2 (Medium), P3 (Low)'
    validations:
      required: true

  - type: input
    id: estimated-hours
    attributes:
      label: Estimated Hours
      description: How many hours do you estimate this task will take?
      placeholder: '8'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: Provide a detailed description of the task
      placeholder: 'Describe what needs to be done...'
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What are the specific criteria for this task to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true

  - type: textarea
    id: technical-requirements
    attributes:
      label: Technical Requirements
      description: Any specific technical requirements or constraints?
      placeholder: 'List any technical requirements...'

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Are there any dependencies on other tasks or issues?
      placeholder: 'List any dependencies...'

  - type: textarea
    id: testing-requirements
    attributes:
      label: Testing Requirements
      description: What testing is required for this task?
      placeholder: 'Unit tests, integration tests, manual testing, etc.'

  - type: textarea
    id: documentation
    attributes:
      label: Documentation Requirements
      description: What documentation needs to be updated or created?
      placeholder: 'API docs, user guides, code comments, etc.'
