name: CI
permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.lock','**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.lock ]; then pip install -r requirements.lock; \
          elif [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install flake8 pytest pytest-cov mypy bandit pip-audit safety

      - name: Lint (flake8)
        run: flake8 || true

      - name: Type check (mypy)
        run: mypy || true

      - name: Security scan (bandit)
        run: bandit -r . || true

      - name: Dependency audit (pip-audit)
        run: |
          pip-audit --progress spinner || true

      - name: Dependency vulnerability check (safety)
        run: |
          safety check || true

      - name: Run tests with coverage
        run: |
          pytest --cov=./ --cov-report=xml:coverage.xml -q || true

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
